version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kfnext-ec2-management"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ozz5611xqtsn"
s3_prefix = "kfnext-ec2-management"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
